FROM python:slim
ENV DISPLAY=:0
ENV MOZ_HEADLESS=1
ENV WEBDRIVER=https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-linux32.tar.gz
RUN apt-get -y update && apt-get -y install\
  firefox-esr \
  wget \
  unzip \
  libnss3 \
   && rm -rf /var/lib/apt/lists/*
RUN pip install selenium
RUN wget $WEBDRIVER -P /tmp && tar xvfz /tmp/${WEBDRIVER##*/} -C /usr/local/bin/ && rm /tmp/${WEBDRIVER##*/}
WORKDIR /workdir
COPY firefox.py .
CMD ./firefox.py
